version: "3"

services:
  scaventum-www:
    build:
      context: .docker/www
      dockerfile: Dockerfile
    container_name: scaventum-www
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - .:/var/www/html:cached
    networks:
      - scaventum
  scaventum-mysql:
    image: mysql:5.7
    container_name: scaventum-mysql
    ports:
      - "3306:3306"
    volumes:
      - scaventum-mysqldata:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=scaventum
      - TZ=Pacific/Auckland
    networks:
      - scaventum
  scaventum-redis:
    image: redis:alpine
    container_name: scaventum-redis
    volumes:
      - scaventum-redisdata:/data
    networks:
      - scaventum
  scaventum-mailhog:
    image: mailhog/mailhog:latest
    container_name: scaventum-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - scaventum

networks:
  scaventum:
    driver: "bridge"

volumes:
  scaventum-mysqldata:
    driver: "local"
  scaventum-redisdata:
    driver: "local"

